# Generated by Django 5.0.1 on 2024-01-07 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacjenci', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(default='', max_length=100)),
                ('nazwisko', models.CharField(default='', max_length=100)),
                ('specjalizacja', models.CharField(max_length=100)),
                ('numer_pwz', models.CharField(default='0000000', max_length=7, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Konsultacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_problemu', models.TextField(max_length=200)),
                ('data_konsultacji', models.DateTimeField()),
                ('zrealizowana', models.BooleanField(default=False)),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsultacje_pacjenta', to='pacjenci.pacjent')),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konsultacje_lekarza', to='lekarze.lekarz')),
            ],
        ),
        migrations.CreateModel(
            name='Plik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plik', models.FileField(upload_to='pliki_konsultacji/')),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('konsultacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pliki', to='lekarze.konsultacja')),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
